version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - flask-net

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_XRAY_DAEMON_ADDRESS=xray-daemon:2000
      - AWS_XRAY_TRACING_NAME=FlaskApp
      - AWS_REGION=eu-central-1
    ports:
      - "5000"
    networks:
      - flask-net
    volumes:
      - .:/flask-app
    depends_on:
      - redis
      - xray-daemon
    image: flask-app
    labels:
      - "traefik.http.routers.flask.rule=Host(`localhost`)"
      - "traefik.port=5000"

  xray-daemon:
    image: amazon/aws-xray-daemon:3.3.13
    container_name: xray-daemon
    command: ["-o", "-n", "eu-central-1"]
    networks:
      - flask-net
    ports:
      - "2000:2000/udp"

  traefik:
    image: "traefik:v2.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    networks:
      - flask-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  flask-net:
    driver: bridge